### ISSUE TITLE
Add `to_slug` func to slugify string

### ISSUE THREAD

**Issue by dwisiswant0** [projectdiscovery/dsl#169]
Example use case:

```yaml
headless:
  - steps:
      - action: navigate
        args:
          url: "{{BaseURL}}"
      - action: waitload
      - action: screenshot
        args:
          fullpage: true
          to: "/path/to/Screenshots/{{to_slug(concat("Screenshot", "-", BaseURL, "-", date_time("%Y-%M-%D-%H-%m")))}}"
          # Output of DSL: Screenshot-https-www-nytimes-com-2024-09-13-22-54
```
