### ISSUE TITLE
Update `llm_prompt` to include latest models from OpenAI and optionally accept model name

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/dsl#220]
```yaml
# existing example
http:
  - raw:
      - |
        POST / HTTP/1.1
        Host: {{Hostname}}
        
        {{llm_prompt('this is existing example with default model')}}
```

```yaml
# new example
http:
  - raw:
      - |
        POST / HTTP/1.1
        Host: {{Hostname}}
        
        {{llm_prompt('this is new example with optional model input', 'gpt4o')}}
```
